### ISSUE TITLE
frzr

### ISSUE THREAD

**Issue by dennis1248** [Malix-Labs/awesome_atomic#97]
https://github.com/ChimeraOS/chimeraos uses https://github.com/ChimeraOS/frzr to provide immutability

I think this was one of the first proper Brtfs-based immutables.

Technology is very similar to [Arkane Linux](https://github.com/arkanelinux), it utilizes exported Btrfs subvolumes.

A talk at Arch Conf 2020 on the technology behind it;
https://youtu.be/WkIGUuVLrn8

**Comment by Malix-Labs** [comment]
Agreed !

Feel free to submit a PR

**Comment by Malix-Labs** [comment]
> Technology is very similar to [Arkane Linux](https://github.com/arkanelinux)

Do you mean https://github.com/arkanelinux/arkdep ?

**Comment by dennis1248** [comment]
> > Technology is very similar to [Arkane Linux](https://github.com/arkanelinux)
> 
> Do you mean https://github.com/arkanelinux/arkdep ?

Indeed. Core technology works exactly the same.
